version: '3'
services:

  db_user_data:
    image: mysql:5.7
    #note that specifically declaring a container name has Docker Swarm implications. Since we are not using swarm this has been ignored.
    container_name: db_user_data
    volumes:
      - dbvolume:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "33061:3306"

  python_service:
    restart: always
    build: ./fiat-engine
    environment:
      - MYSQL_HOST=db_user_data
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  backend:
    restart: always
    build: ./web-services/auditing
    ports:
      #DEBUG PORT
      - "50505:50505"
    volumes:
      #Make the code folder visible from within the container
      - ./web-services/auditing:/code
    environment:
      - MYSQL_HOST=db_user_data
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      #set the path as the location within the container after web-services directory is copied.
      - FIREBASE_CRED_PATH=/code/firebase-credentials.json
    depends_on:
      - db_user_data
      - python_service

  frontend:
    restart: always
    build: ./web-ui
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  dbvolume:
