server:
  port: 8888
logging:
  level:
    .: info
    org.springframework: info
spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/CryptoCaddy/web-app
          searchPaths: web-services/config
          username: Zooted
          password: Painting5
#          force-pull: true
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
