info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
logging:
  level:
    .: debug
    org.springframework: debug
spring:
  cloud:
    config:
      enabled: true
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
springfox:
  documentation:
    swagger:
      v2:
        path: "/api-docs"
server:
  contextPath: "/api"
fiat:
  engine:
    base:
      url: http://localhost:7001/api/
binance:
  binancekey:
  binancesecret:
bittrex:
  bittrexkey:
  bittrexsecret:
coinbase:
  coinbasekey:
  coinbasesecret:
gdax:
  gdaxkey:
  gdaxsecret:
  gdaxpass: