logging:
  level:
    .: debug
    org.springframework: debug
spring:
  profiles: local
  cloud:
    config:
      enabled: false

#add keys here to hard coded test functionality. ensure keys are read only and this is in .gitignore file.
binance:
  binancekey: 
  binancesecret:
bittrex:
  bittrexkey:
  bittrexsecret:
coinbase:
  coinbasekey:
  coinbasesecret:
gdax:
  gdaxkey:
  gdaxsecret:
  gdaxpass: