info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
logging:
  level:
    .: info
    org.springframework: info
spring:
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
springfox:
  documentation:
    swagger:
      v2:
        path: "/api-docs"
server:
  contextPath: "/api"
fiat:
  engine:
    base:
      url: http://${FIAT_HOST:"localhost"}:7001/api/
binance:
  binancekey:
  binancesecret:
bittrex:
  bittrexkey:
  bittrexsecret:
coinbase:
  coinbasekey:
  coinbasesecret:
gdax:
  gdaxkey:
  gdaxsecret:
  gdaxpass: